spring:
  datasource:
    url: jdbc:mysql://192.168.198.131:3306/ass?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: rootcc123
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true #该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性


