###
GET http://localhost:8080/doc/tree/project/1
Accept: application/json


###
GET http://localhost:8000/document/getProjectDocTreeById


###
POST http://localhost:8000/api/checkToken

###
GET http://localhost:8080/doc/project/1/parent/9
Accept: application/json

###
GET http://localhost:8080/doc/project/1/parent/3
Accept: application/json

###
GET http://localhost:8080/doc/project/1/parent/2
Accept: application/json



###
GET http://localhost:8080/doc/project/1/parent/1
Accept: application/json
###
GET http://localhost:8080/doc/project/1/parent/0
Accept: application/json




GET http://localhost:8080/project/12
Accept: application/json





###
POST http://localhost:8080/project
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="projectCode"

发动机的EFRDF
--WebAppBoundary--
Content-Disposition: form-data; name="projectName"

发动机MICHENF名称


###


###
GET http://localhost:8080/project
Content-Type: application/json

{
  "current":1,
  "pageSize":10,
  "projectCode":"code",
  "projectName": "名称",



  "searchEndTime": "2021-10-29 00:00:00",
  "searchStartTime": "2021-10-22 00:00:00",
  "sorter": {
    "createAt": "ascend",
    "projectName": "descend"
  }

}

###
#"filter": {
#    "status":[ "created", "initialized" ]
#  },
#
####

GET http://127.0.0.1:8080/project
Content-Type: application/json

{

  "projectCode": "code",
  "projectName": "名称",
  "searchStartTime": "2021-10-12 00:00:00",
  "searchEndTime":"2021-10-27 09:55:00",
  "sorter": {
    "createAt": "ascend",
    "projectName": "descend"
  }

}

<> 2021-10-27T230011.200.json
<> 2021-10-27T221508.200.json
<> 2021-10-27T221501.200.json
<> 2021-10-27T221440.200.json
<> 2021-10-27T221415.200.json
<> 2021-10-27T221329.200.json
<> 2021-10-27T221322.200.json
<> 2021-10-27T221254.200.json
<> 2021-10-27T221232.200.json
<> 2021-10-27T221054.200.json
<> 2021-10-27T221043.200.json
<> 2021-10-27T220957.200.json
<> 2021-10-27T220916.200.json
<> 2021-10-27T220725.200.json
<> 2021-10-27T220707.200.json
<> 2021-10-27T220651.200.json
<> 2021-10-27T220558.200.json
<> 2021-10-27T220207.200.json
<> 2021-10-27T215832.500.json
<> 2021-10-27T215628.200.json
<> 2021-10-27T215541.200.json
<> 2021-10-27T215413.500.json
<> 2021-10-27T215402.405.json

###
POST http://221.226.92.38:5000/api/project/basicList
Content-Type: application/json

{
  "current": 1,
  "pageSize": 20,
  "filter": {
    "status":[ "created", "initialized" ]
  },
  "projectCode": "code",
  "projectName": "name",
  "searchEndTime": "2021-10-22 00:00:00",
  "searchStartTime": "2021-11-22 00:00:00",
  "sorter": {
    "createAt": "ascend",
    "projectName": "descend"
  }
}

