GET http://localhost:8080/project/12
Accept: application/json





###
POST http://localhost:8080/project
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="projectCode"

发动机的EFRDF
--WebAppBoundary--
Content-Disposition: form-data; name="projectName"

发动机MICHENF名称


###


###
GET http://localhost:8080/project
Content-Type: application/json

{
  "current":1,
  "pageSize":10,
  "projectCode":"code",
  "projectName": "名称",



  "searchEndTime": "2021-10-29 00:00:00",
  "searchStartTime": "2021-10-22 00:00:00",
  "sorter": {
    "createAt": "ascend",
    "projectName": "descend"
  }

}

###
#"filter": {
#    "status":[ "created", "initialized" ]
#  },
#
####


